import { z } from "zod"

export const accidentVehicleSchema = z.object({
  vehicleNumber: z.number().int().optional(),
  licensePlate: z.string().min(1),
  vehicleType: z.string(),
  brand: z.string().optional(),
  model: z.string().optional(),
  color: z.string().optional(),
  registrationYear: z.number().int().optional(),
  vin: z.string().optional(),
  directionOfTravel: z.string().optional(),
  maneuver: z.string().optional(),
  isFugitive: z.boolean().optional().default(false),
  insuranceCompany: z.string().optional(),
  insurancePolicy: z.string().optional(),
  insuranceExpiry: z.string().datetime().optional(),
  insuranceValid: z.boolean().optional(),
  revisionDate: z.string().optional(),
  mitDataFetchedAt: z.string().datetime().optional(),
  damageDescription: z.string().optional(),
  damageAreas: z.array(z.string()).optional().default([]),
  damageZones: z.any().optional(),
  deformationType: z.string().optional(),
  airbagDeployed: z.boolean().optional(),
  tireCondition: z.string().optional(),
  ownerName: z.string().optional(),
  ownerFiscalCode: z.string().optional(),
  ownerAddress: z.string().optional(),
  towingRequired: z.boolean().optional().default(false),
  towingCompany: z.string().optional(),
  towingAt: z.string().datetime().optional(),
  depositLocation: z.string().optional(),
  position: z.enum(["VEICOLO_A", "VEICOLO_B", "VEICOLO_C"]).optional(),
})

export const accidentPersonSchema = z.object({
  role: z.string(),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  fiscalCode: z.string().optional(),
  birthDate: z.string().datetime().optional(),
  birthPlace: z.string().optional(),
  nationality: z.string().optional(),
  documentType: z.string().optional(),
  documentNumber: z.string().optional(),
  address: z.string().optional(),
  contactPhone: z.string().optional(),
  email: z.string().email().optional().or(z.literal("")),
  licenseNumber: z.string().optional(),
  licenseCategory: z.string().optional(),
  licenseExpiry: z.string().datetime().optional(),
  licenseValid: z.boolean().optional(),
  seatbeltUsed: z.boolean().optional(),
  isFugitive: z.boolean().optional().default(false),
  injuries: z.string().optional(),
  injuriesDetail: z.string().optional(),
  injuryDescription: z.string().optional(),
  hospitalSentTo: z.string().optional(),
  transportedBy: z.string().optional(),
  alcoholTestDone: z.boolean().optional(),
  alcoholTestResult: z.number().optional(),
  drugTestDone: z.boolean().optional(),
  drugTestResult: z.string().optional(),
  statement: z.string().optional(),
  refused689: z.boolean().optional().default(false),
  notified689At: z.string().datetime().optional(),
  vehicleIndex: z.number().optional().nullable(),
})

export const accidentTraceSchema = z.object({
  code: z.string().min(1),
  type: z.string(),
  photoUrl: z.string().optional(),
  position: z.string().optional(),
  measurement: z.string().optional(),
  dimensions: z.string().optional(),
  description: z.string().optional(),
})

export const accidentDeclarationSchema = z.object({
  personId: z.string(),
  type: z.enum(["SPONTANEA", "SU_INVITO", "S.I.T.", "RIFIUTO"]),
  content: z.string().min(1),
  signedByPerson: z.boolean().optional().default(false),
  signatureImageUrl: z.string().optional(),
  legalWarningGiven: z.boolean().optional().default(false),
  refused: z.boolean().optional().default(false),
})

export const accidentSurveySchema = z.object({
  roadType: z.enum(["URBANA", "EXTRAURBANA", "AUTOSTRADA", "PISTA_CICLABILE"]).optional(),
  roadName: z.string().optional(),
  roadWidth: z.number().optional(),
  laneCount: z.number().int().optional(),
  speedLimit: z.number().int().optional(),
  slopeType: z.enum(["PIANO", "SALITA", "DISCESA", "CURVA"]).optional(),
  slopePercent: z.number().optional(),
  impactZoneDesc: z.string().optional(),
  impactMeasures: z.any().optional(),
  skidMarksLength: z.number().optional(),
  debrisDescription: z.string().optional(),
  signagePresent: z.array(z.string()).optional().default([]),
  signageDamaged: z.boolean().optional().default(false),
  roadMarkingsPresent: z.boolean().optional().default(false),
  trafficLightPresent: z.boolean().optional().default(false),
  trafficLightWorking: z.boolean().optional(),
  guardRailDamaged: z.boolean().optional().default(false),
  publicLightingDamaged: z.boolean().optional().default(false),
  otherDamages: z.string().optional(),
})

export const accidentExternalUnitSchema = z.object({
  unitType: z.enum(["VVF", "118", "POLIZIA_STATO", "CARABINIERI", "GDF", "ANAS", "COMUNE", "ALTRO"]),
  unitName: z.string().optional(),
  unitIdentifier: z.string().optional(),
  arrivedAt: z.string().datetime().optional(),
  leftAt: z.string().datetime().optional(),
  officerInCharge: z.string().optional(),
  actionsPerformed: z.string().optional(),
  reportNumber: z.string().optional(),
  notes: z.string().optional(),
})

export const accidentSendEmailSchema = z.object({
  recipients: z.array(z.object({
    email: z.string().email(),
    recipientType: z.enum(["CONDUCENTE", "ASSICURAZIONE", "PROPRIETARIO", "OSPEDALE", "ENTE", "PREFETTURA"]),
    name: z.string().optional(),
  })),
  subject: z.string().optional(),
  customMessage: z.string().optional(),
})

export const createAccidentSchema = z.object({
  date: z.string().datetime(),
  address: z.string().min(1),
  lat: z.number().optional(),
  lng: z.number().optional(),
  locationNotes: z.string().optional(),
  eventType: z.string().optional(),
  severity: z.enum(["SOLO_DANNI", "FERITI", "MORTALE", "RISERVA_PROGNOSI"]),
  roadType: z.string().optional(),
  roadGeometry: z.string().optional(),
  roadSignage: z.string().optional(),
  lanesNumber: z.number().optional(),
  speedLimit: z.number().optional(),
  trafficLight: z.string().optional(),
  lighting: z.string().optional(),
  weatherCondition: z.string().optional(),
  roadCondition: z.string().optional(),
  trafficCondition: z.string().optional(),
  safetyChecklist: z.array(z.string()).optional().default([]),
  dynamicDescription: z.string().optional(),
  dynamicDiagramUrl: z.string().optional(),
  narrativeReport: z.string().optional(),
  legalFramework: z.enum(["CIVILE", "PENALE", "ENTRAMBI"]).optional(),
  penalArticles: z.array(z.string()).optional().default([]),
  administrativeRef: z.string().optional(),
  interventionId: z.string().optional(),
  reportingOfficerId: z.string().optional(),
  secondOfficerId: z.string().optional(),
  supervisorId: z.string().optional(),
  receivedAt: z.string().datetime().optional(),
  arrivedAt: z.string().datetime().optional(),
  closedAt: z.string().datetime().optional(),
  notes: z.string().optional(),
  vehicles: z.array(accidentVehicleSchema).optional(),
  people: z.array(accidentPersonSchema).optional(),
})
